# This file has been generated by node2nix 1.3.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@iamadamjowett/angular-click-outside-2.10.1" = {
      name = "@iamadamjowett/angular-click-outside";
      packageName = "@iamadamjowett/angular-click-outside";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iamadamjowett/angular-click-outside/-/angular-click-outside-2.10.1.tgz";
        sha1 = "01cacdb982c2c86ab912dc329c6f18ec5704e338";
      };
    };
    "angular-1.5.11" = {
      name = "angular";
      packageName = "angular";
      version = "1.5.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular/-/angular-1.5.11.tgz";
        sha1 = "8c5ba7386f15965c9acf3429f6881553aada30d6";
      };
    };
    "angular-cache-4.6.0" = {
      name = "angular-cache";
      packageName = "angular-cache";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-cache/-/angular-cache-4.6.0.tgz";
        sha1 = "5cc90ad1273fb150205dc1c71b8141ae39e48bff";
      };
    };
    "angular-route-1.5.11" = {
      name = "angular-route";
      packageName = "angular-route";
      version = "1.5.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-route/-/angular-route-1.5.11.tgz";
        sha1 = "49614f3a167f54291e449fe8ba05d39c58924b83";
      };
    };
    "angular-sanitize-1.5.11" = {
      name = "angular-sanitize";
      packageName = "angular-sanitize";
      version = "1.5.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-sanitize/-/angular-sanitize-1.5.11.tgz";
        sha1 = "ebfb3f343e543f9b2ef050fb4c2e9ee048d1772f";
      };
    };
    "angular-ui-bootstrap-2.5.6" = {
      name = "angular-ui-bootstrap";
      packageName = "angular-ui-bootstrap";
      version = "2.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-ui-bootstrap/-/angular-ui-bootstrap-2.5.6.tgz";
        sha512 = "3qcy9ddj9rh9ykqw57jp2x4rd39z5fnw6xzq0ynp4l3vnvs2b9lqgqf3fkbhjq188scqx1xai60a8729xpcxhv9vwv5shhbyfj0fdyb";
      };
    };
    "angular-uuid4-0.3.1" = {
      name = "angular-uuid4";
      packageName = "angular-uuid4";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-uuid4/-/angular-uuid4-0.3.1.tgz";
        sha1 = "b8b50beb10cebff4ba52312fd7bd4ed8d99b49d7";
      };
    };
    "jquery-timepicker-1.3.3" = {
      name = "jquery-timepicker";
      packageName = "jquery-timepicker";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-timepicker/-/jquery-timepicker-1.3.3.tgz";
        sha1 = "034160c90a52619df68963eda7625d1fca89cb7a";
      };
    };
    "ngclipboard-1.1.2" = {
      name = "ngclipboard";
      packageName = "ngclipboard";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ngclipboard/-/ngclipboard-1.1.2.tgz";
        sha1 = "459f01f3ee1e8ac401599aaea37b9775087d596d";
      };
    };
    "ui-select-0.19.8" = {
      name = "ui-select";
      packageName = "ui-select";
      version = "0.19.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ui-select/-/ui-select-0.19.8.tgz";
        sha1 = "74860848a7fd8bc494d9856d2f62776ea98637c1";
      };
    };
    "vcard-parser-0.2.7" = {
      name = "vcard-parser";
      packageName = "vcard-parser";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/vcard-parser/-/vcard-parser-0.2.7.tgz";
        sha1 = "58673c582410c36381e0731d771e07d121279de7";
      };
    };
    "jquery-3.2.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.2.1.tgz";
        sha1 = "5c4d9de652af6cd0a770154a631bba12b015c787";
      };
    };
    "clipboard-1.5.16" = {
      name = "clipboard";
      packageName = "clipboard";
      version = "1.5.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/clipboard/-/clipboard-1.5.16.tgz";
        sha1 = "916d5e739b0064be61b0b48a535731ecaef3d367";
      };
    };
    "good-listener-1.2.2" = {
      name = "good-listener";
      packageName = "good-listener";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/good-listener/-/good-listener-1.2.2.tgz";
        sha1 = "d53b30cdf9313dffb7dc9a0d477096aa6d145c50";
      };
    };
    "select-1.1.2" = {
      name = "select";
      packageName = "select";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/select/-/select-1.1.2.tgz";
        sha1 = "0e7350acdec80b1108528786ec1d4418d11b396d";
      };
    };
    "tiny-emitter-1.2.0" = {
      name = "tiny-emitter";
      packageName = "tiny-emitter";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-emitter/-/tiny-emitter-1.2.0.tgz";
        sha1 = "6dc845052cb08ebefc1874723b58f24a648c3b6f";
      };
    };
    "delegate-3.1.3" = {
      name = "delegate";
      packageName = "delegate";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegate/-/delegate-3.1.3.tgz";
        sha1 = "9a8251a777d7025faa55737bc3b071742127a9fd";
      };
    };
  };
  args = {
    name = "contacts";
    packageName = "contacts";
    version = "2.0.1";
    src = ./.;
    dependencies = [
      sources."@iamadamjowett/angular-click-outside-2.10.1"
      sources."angular-1.5.11"
      sources."angular-cache-4.6.0"
      sources."angular-route-1.5.11"
      sources."angular-sanitize-1.5.11"
      sources."angular-ui-bootstrap-2.5.6"
      sources."angular-uuid4-0.3.1"
      (sources."jquery-timepicker-1.3.3" // {
        dependencies = [
          sources."jquery-3.2.1"
        ];
      })
      (sources."ngclipboard-1.1.2" // {
        dependencies = [
          (sources."clipboard-1.5.16" // {
            dependencies = [
              (sources."good-listener-1.2.2" // {
                dependencies = [
                  sources."delegate-3.1.3"
                ];
              })
              sources."select-1.1.2"
              sources."tiny-emitter-1.2.0"
            ];
          })
        ];
      })
      sources."ui-select-0.19.8"
      sources."vcard-parser-0.2.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Place this app in **nextcloud/apps/**";
      homepage = "https://github.com/nextcloud/contacts#readme";
      license = "AGPL-3.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}